### ISSUE TITLE
pdf release sections out of order

### ISSUE THREAD

**Issue by Tactile-Taco** [ryan4yin/nixos-and-flakes-book#179]
The sections of the book release pdf are out of order. It begins with "Adding Binary Cache Servers" as the first section. The preface comes later and it seems to be the correct order after that, however I do not know the full organization of the book so I can't say for sure.

**Comment by 42Willow** [comment]
https://github.com/ryan4yin/nixos-and-flakes-book/compare/v0.4.1...v0.4.2

Broke somewhere here I believe

**Comment by dcolestock** [comment]
Generating the pdf build of the current 359c1195827f1aa50b7ead6ad8249fb653e78cd2 commit with

```bash
git clone git@github.com:ryan4yin/nixos-and-flakes-book.git
cd nixos-and-flakes-book/
nix develop .#export-pdf --ignore-environment --command bash -c '
            pnpm install
            pnpm export-pdf
          '
```
reveals the issue is fixed.  It goes right into the preface.  I was also able to replicate the original issue by switching back to tag v0.4.2 and generating the pdf again, so it appears to be fixed somewhere between the then and now.

**Comment by ryan4yin** [comment]
@dcolestock Thanks for the feedback, I add a new tag https://github.com/ryan4yin/nixos-and-flakes-book/releases/tag/v0.4.4 and confirmed the issue is gone.
